### ISSUE TITLE
用户升级后的消息提示里应该是链接的字段点了没反应

### ISSUE THREAD

**Issue by Qing-Novel** [realth000/tsdm_client#153]
https://github.com/user-attachments/assets/0e1760db-db52-4f71-8da9-816178dbae8d

**Comment by realth000** [comment]
点不开的链接网址是多少？我这没有这种消息

**Comment by Qing-Novel** [comment]
> 点不开的链接网址是多少？我这没有这种消息

我稍后发

**Comment by Qing-Novel** [comment]
昼天使：https://www.tsdm39.com/home.php?mod=spacecp&ac=credit&op=usergroup
看看我能做什么：https://www.tsdm39.com/home.php?mod=spacecp&ac=usergroup

**Comment by Qing-Novel** [comment]
链接已经发了，佬看下哈

**Comment by realth000** [comment]
别急，没下班呢

**Comment by Qing-Novel** [comment]
> 别急，没下班呢

好的好的

**Comment by realth000** [comment]
复现不出来，是可以跳转到浏览器的

**Comment by Qing-Novel** [comment]
> 复现不出来，是可以跳转到浏览器的

啊？那我再试试

**Comment by Qing-Novel** [comment]
不对啊，我这边点了确实不行啊。。。

**Comment by realth000** [comment]
过几天家加点调试的办法吧

**Comment by Qing-Novel** [comment]
> 过几天加点调试的办法吧

好的，辛苦佬了

**Comment by realth000** [comment]
https://github.com/realth000/tsdm_client/actions/runs/12529835475

用这里的apk，去设置里把 调试 -> 启用调试操作 打开

然后回到消息页面，在通知卡片右上角的菜单里选择“拷贝原始内容”，把拷贝的内容发出来

**Comment by Qing-Novel** [comment]
> https://github.com/realth000/tsdm_client/actions/runs/12529835475
> 
> 用这里的apk，去设置里把 调试 -> 启用调试操作 打开
> 
> 然后回到消息页面，在升级提醒的卡片右上角菜单里选择“拷贝原始内容”，把拷贝的内容发出来

好的

**Comment by Qing-Novel** [comment]
您的用户组升级为 <a href="home.php?mod=spacecp&ac=credit&op=usergroup">昼天使</a> &nbsp; <a href="home.php?mod=spacecp&ac=usergroup" target="_blank" class="lit">看看我能做什么 &rsaquo;</a>

**Comment by Qing-Novel** [comment]
这功能不错，别删了吧（

**Comment by Qing-Novel** [comment]
以防万一我把复制出来的代码做个txt
[代码.txt](https://github.com/user-attachments/files/18268107/default.txt)

**Comment by realth000** [comment]
可以用markdown的代码块

```
\`\`\`
\`\`\`
```

**Comment by realth000** [comment]
单从内容上看看不出问题，等晚上回来试试，我今天加班。

晚上不一定有时间吧，论坛上有事情要处理。

这事不急，只涉及这一种通知（

**Comment by Qing-Novel** [comment]
好的

**Comment by Qing-Novel** [comment]
> 单从内容上看看不出问题，等晚上回来试试，我今天加班。
> 
> 晚上不一定有时间吧，论坛上有事情要处理。
> 
> 这事不急，只涉及这一种通知（

好的

**Comment by Qing-Novel** [comment]
佬，这个调试功能感觉挺好的，就别删了呗，要是怕人乱搞，可以整的位置隐藏点，比如关于点5次版本号才能在设置页显示调试功能

**Comment by realth000** [comment]
也按照这里的步骤操作一次，把日志贴出来：

https://github.com/realth000/tsdm_client/issues/158#issuecomment-2567172629

**Comment by Qing-Novel** [comment]
> 也按照这里的步骤操作一次，把日志贴出来：
> 
> [#158 (comment)](https://github.com/realth000/tsdm_client/issues/158#issuecomment-2567172629)

好的

**Comment by Qing-Novel** [comment]
https://github.com/user-attachments/assets/008ba44c-e074-4cd9-bdb2-602aeeeb0a62

[debug] | 8:10:02 384ms | start app...
[debug] | 8:10:02 392ms | connect to database
[debug] | 8:10:02 392ms | init database file at /data/user/0/kzs.th000.tsdm_clienu/files/db/mainV2.db
[debug] | 8:10:02 406ms | load cookie from database with login user uid: ****419
[debug] | 8:10:02 406ms | build no-cookie with cookie: null
[debug] | 8:10:02 421ms | RootLocationCubit: enter page /homepage
[debug] | 8:10:02 426ms | ForumHomeRepository: fetch home page
[debug] | 8:10:02 426ms | build cookie with user info: null
[debug] | 8:10:02 427ms | ProfileRepository: fetch profile page v2
[debug] | 8:10:02 427ms | build cookie with user info: null
[debug] | 8:10:05 64ms | ForumHomeRepository: use fetched home page
[debug] | 8:10:05 66ms | CookieProvider: save authed cookie to storage
[debug] | 8:10:05 74ms | AuthenticationRepository: save logged user info: UserLoginInfo{ username=********用, uid=****419, 
[debug] | 8:10:05 85ms | CookieProvider: update user info: UserLoginInfo{ username=********用, uid=****419, 
[debug] | 8:10:05 86ms | CookieProvider: complete user info updated, sync cookie
[debug] | 8:10:05 90ms | AuthenticationRepository: login with document: user UserLoginInfo{ username=********用, uid=****419, 
[debug] | 8:10:05 94ms | NotificationBloc: updating all notifications...
[debug] | 8:10:05 157ms | NotificationBloc: fetch notification since 2024-12-29 21:14:42
[debug] | 8:10:05 158ms | build cookie with user info: null
[error] | 8:10:05 173ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: TR83, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: 黑影君, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: YQ17, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: lin1996, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: dodo_123, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: ruik0, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: x852659347, imageUrl: ): empty image url
[error] | 8:10:05 174ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: dean1116tw, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: yoruamei, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: lwq597521, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: 你jia乐, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: 先果后因, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: goodname59, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: xuxu0037, imageUrl: ): empty image url
[error] | 8:10:05 175ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: hshsa, imageUrl: ): empty image url
[error] | 8:10:05 176ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: HACKERYJA, imageUrl: ): empty image url
[error] | 8:10:05 176ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: Misaka-Network, imageUrl: ): empty image url
[error] | 8:10:05 176ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: sgsqx, imageUrl: ): empty image url
[error] | 8:10:05 176ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: aaando, imageUrl: ): empty image url
[error] | 8:10:05 177ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: lalaufoxy, imageUrl: ): empty image url
[error] | 8:10:05 177ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: Mike57, imageUrl: ): empty image url
[error] | 8:10:05 177ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: 是莫莫喵, imageUrl: ): empty image url
[error] | 8:10:05 177ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: qicaiyunjian, imageUrl: ): empty image url
[error] | 8:10:05 178ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: hlhuz, imageUrl: ): empty image url
[error] | 8:10:05 178ms | failed to render image: failed to load image for ImageCacheUserAvatarRequest(username: 洛艾爾, imageUrl: ): empty image url
[debug] | 8:10:06 830ms | NotificationBloc: saving notification: notice=0 personalMessage=0 broadcastMessage=0
[debug] | 8:10:06 833ms | NotificationBloc: load local notification: notice=52 personalMessage=0 broadcastMessage=2
[debug] | 8:10:07 516ms | RootLocationCubit: enter page /settings
[debug] | 8:10:11 259ms | RootLocationCubit: enter page /debugLog
[debug] | 8:10:16 707ms | RootLocationCubit: leave page /debugLog
[exception] | 8:10:17 424ms | 
PathAccessException: Creation failed, path = '/storage/emulated/0/download/tsdm_client' (OS Error: Permission denied, errno = 13)
StackTrace: #0      _checkForErrorResponse (dart:io/common.dart:56)
#1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109)
#2      _rootRunUnary (dart:async/zone.dart:1422)
<asynchronous suspension>
#3      _SettingsPageState._buildDebugSection.<anonymous closure> (package:tsdm_client/features/settings/view/settings_page.dart:736)
<asynchronous suspension>
}
[debug] | 8:10:32 529ms | RootLocationCubit: enter page /debugLog
[debug] | 8:11:33 1ms | RootLocationCubit: leave page /debugLog
[debug] | 8:14:09 571ms | RootLocationCubit: enter page /debugLog
[debug] | 8:15:02 642ms | RootLocationCubit: leave page /debugLog
[debug] | 8:15:07 214ms | RootLocationCubit: enter page /notice
[debug] | 8:15:09 756ms | dispatch url: home.php?mod=spacecp&ac=credit&op=usergroup
[debug] | 8:15:09 760ms | NotificationBloc: mark notice: RecordMarkNotice(uid: 2095419, nid: 9468321, alreadyRead: true)
[exception] | 8:15:09 768ms | 
PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { home.php?mod=spacecp&ac=credit&op=usergroup }, null, null)
StackTrace: #0      UrlLauncherAndroid.launchUrl (package:url_launcher_android/url_launcher_android.dart:122)
<asynchronous suspension>
#1      DispatchUrl.dispatchAsUrl (package:tsdm_client/extensions/build_context.dart:49)
<asynchronous suspension>
}
[debug] | 8:15:10 421ms | dispatch url: home.php?mod=spacecp&ac=usergroup
[debug] | 8:15:10 422ms | NotificationBloc: mark notice: RecordMarkNotice(uid: 2095419, nid: 9468321, alreadyRead: true)
[exception] | 8:15:10 426ms | 
PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { home.php?mod=spacecp&ac=usergroup }, null, null)
StackTrace: #0      UrlLauncherAndroid.launchUrl (package:url_launcher_android/url_launcher_android.dart:122)
<asynchronous suspension>
#1      DispatchUrl.dispatchAsUrl (package:tsdm_client/extensions/build_context.dart:49)
<asynchronous suspension>
}
[debug] | 8:15:10 821ms | dispatch url: home.php?mod=spacecp&ac=credit&op=usergroup
[debug] | 8:15:10 823ms | NotificationBloc: mark notice: RecordMarkNotice(uid: 2095419, nid: 9468321, alreadyRead: true)
[exception] | 8:15:10 835ms | 
PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { home.php?mod=spacecp&ac=credit&op=usergroup }, null, null)
StackTrace: #0      UrlLauncherAndroid.launchUrl (package:url_launcher_android/url_launcher_android.dart:122)
<asynchronous suspension>
#1      DispatchUrl.dispatchAsUrl (package:tsdm_client/extensions/build_context.dart:49)
<asynchronous suspension>
}
[debug] | 8:15:11 71ms | dispatch url: home.php?mod=spacecp&ac=usergroup
[debug] | 8:15:11 72ms | NotificationBloc: mark notice: RecordMarkNotice(uid: 2095419, nid: 9468321, alreadyRead: true)
[exception] | 8:15:11 75ms | 
PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { home.php?mod=spacecp&ac=usergroup }, null, null)
StackTrace: #0      UrlLauncherAndroid.launchUrl (package:url_launcher_android/url_launcher_android.dart:122)
<asynchronous suspension>
#1      DispatchUrl.dispatchAsUrl (package:tsdm_client/extensions/build_context.dart:49)
<asynchronous suspension>
}
[debug] | 8:15:12 146ms | RootLocationCubit: leave page /notice
[exception] | 8:15:15 391ms | 
PathAccessException: Creation failed, path = '/storage/emulated/0/download/tsdm_client' (OS Error: Permission denied, errno = 13)
StackTrace: #0      _checkForErrorResponse (dart:io/common.dart:56)
#1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109)
#2      _rootRunUnary (dart:async/zone.dart:1422)
<asynchronous suspension>
#3      _SettingsPageState._buildDebugSection.<anonymous closure> (package:tsdm_client/features/settings/view/settings_page.dart:736)
<asynchronous suspension>
}
[debug] | 8:15:16 718ms | RootLocationCubit: enter page /debugLog

**Comment by Qing-Novel** [comment]
[日志.txt](https://github.com/user-attachments/files/18287015/default.txt)

**Comment by realth000** [comment]
贴日志的时候放到code block里吧，前后各加一行，分别写上三个`
不然会被识别成普通文本链接到其它issue上

**Comment by Qing-Novel** [comment]
> 贴日志的时候放到code block里吧，前后各加一行，分别写上三个` 不然会被识别成普通文本链接到其它issue上

行，下次这么做

**Comment by realth000** [comment]
试试这里的
https://github.com/realth000/tsdm_client/actions/runs/12607462496

**Comment by realth000** [comment]
> 试试这里的 https://github.com/realth000/tsdm_client/actions/runs/12607462496

同时试一下 #158  吧，看看修好没

**Comment by Qing-Novel** [comment]
> > 试试这里的 https://github.com/realth000/tsdm_client/actions/runs/12607462496
> 
> 同时试一下 #158 吧，看看修好没

行
